name: server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  shelf: ^1.1.1
  shelf_web_socket:
  web_socket_channel: ^2.2.0
  sqlite3:
  sqflite_common_ffi:

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
